name: "Test input reflection"

on:
  workflow_dispatch:
    inputs:
      cloudfront_distribution_id:
        description: "ID of the CloudFront distribution to invalidate"
        required: true
      invalidation_paths:
        description: "Paths to invalidate (space separated)"
        required: true

jobs:
  invalidate_cache:
    name: Invalidate CloudFront distribution cache
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Test input reflection
        run: |
            echo ${{inputs.invalidation_paths}}
